name: zt-firewall-suite
description: ZeroTier-Aware DevOps Suite with Firewall + VNC + Docker Swarm
url: https://yourusername.github.io/zt-firewall-suite/ 
hook_url: https://yourusername.github.io/zt-firewall-suite/webhook 
redirect_url: https://yourusername.github.io/zt-firewall-suite/setup 
setup_url: /setup
default_permissions:
  contents: read
  actions: write
  packages: write
default_events:
  - push
  - release
  - pull_request
  - workflow_run
  - installation
public: true
webhook_active: false