name: Integration Test

on:
  push:
    branches: [main]

jobs:
  integration-test:
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    runs-on: ubuntu-latest

    steps:
      - name: Setup QEMU and Docker
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Test Container for ${{ matrix.arch }}
        run: |
          docker build -t zt-firewall-test-$ARCH --build-arg TARGETARCH=${{ matrix.arch }} - <<EOT
          FROM --platform=linux/${{ matrix.arch }} ubuntu:latest
          RUN apt update && apt install -y nftables curl jq
          COPY install-firewall.sh /install-firewall.sh
          RUN chmod +x /install-firewall.sh
          CMD ["bash"]
EOT

      - name: Run Firewall Test
        run: |
          docker run --privileged zt-firewall-test-$ARCH /bin/bash -c "sudo ./install-firewall.sh && sudo fwctl status"