name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: zt-firewall-ubuntu-latest-x86_64
          path: dist/ubuntu-x86_64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          body: |
            ## Changelog
            
            ${{ github.event.head_commit.message }}
          files: 
            dist/ubuntu-x86_64/*