name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y nftables jq shellcheck docker.io

      - name: Run Test Suite
        run: |
          chmod +x test-suite.sh
          ./test-suite.sh